export const GET_QUESTIONS = "GET_QUESTIONS";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const SET_QUESTION_INDEX = "SET_QUESTION_INDEX";
export const TOGGLE_MENU_AVAILABLE = "TOGGLE_MENU_AVAILABLE";
export const TOGGLE_SHOW_MENU = "TOGGLE_SHOW_MENU";
