export const SET_STEP = "SET_STEP";
export const TOGGLE_MENU_AVAILABLE = "TOGGLE_MENU_AVAILABLE";
export const TOGGLE_SHOW_MENU = "TOGGLE_SHOW_MENU";
export const SET_QUESTION_INDEX = "SET_QUESTION_INDEX";
export const SET_BOOKMARKS = "SET_BOOKMARKS";
