export const SET_STEP = "SET_STEP";
export const TOGGLE_MENU_AVAILABLE = "TOGGLE_MENU_AVAILABLE";
export const TOGGLE_SHOW_MENU = "TOGGLE_SHOW_MENU";
export const SET_QUESTION_INDEX = "SET_QUESTION_INDEX";
export const SET_BOOKMARKS = "SET_BOOKMARKS";
export const TOGGLE_SUBMITTING = "TOGGLE_SUBMITTING";
export const TOGGLE_SUBMITTED = "TOGGLE_SUBMITTED";
export const SET_CORRECT_COUNT = "SET_CORRECT_COUNT";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
